Repository Project-Stage-Academy/UA_1340_alpha, pull requests merged in 2025-03, with the labels that each got.

#122 22 Implementing serializers
  forum/communications/serializers.py
  forum/investors/serializers.py
  forum/projects/serializers.py
  forum/startups/serializers.py
Labels: task

#148 Hot fix to repair main branch
  .gitignore
  forum/investors/serializers.py
Labels: bug

#150 added swagger schemas
  forum/users/views.py
Labels: improvement

#153 Bug fix user permission
  forum/users/migrations/0003_user_groups_user_user_permissions.py
  forum/users/models.py
Labels: bug

#149 Setup django channels
  forum/communications/consumers.py
  forum/communications/routing.py
  forum/forum/asgi.py
  forum/forum/settings.py
  requirements.txt
Labels: sub-task

#152 Backend setup for o auth integration 95/96
  .env.example
  forum/forum/settings.py
  forum/users/urls.py
  requirements.txt
Labels: sub-task
